language: python
addons:
  postgresql: "9.4"
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

install:
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - export DATABASE_URL=postgres://postgres:@localhost:5432/calendly_helper
  - psql -c 'create database calendly_helper;' -U postgres

script:
  - coverage run --source='.' --omit='env/*,*/migrations/*,manage.py' manage.py test --noinput

after_script:
  - codecov
