language: python
addons:
  postgresql: "9.4"
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

# https://docs.travis-ci.com/user/caching/#before_cache-phase
cache:
  directories:
    - $HOME/.cache/pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

install:
  - pip install -r requirements.txt
  - pip install codecov

before_script:
  - export DATABASE_URL=postgres://postgres:@localhost:5432/calendly_helper
  - psql -c 'create database calendly_helper;' -U postgres

script:
  - python manage.py collectstatic
  - coverage run --source='.' --omit='env/*,*/migrations/*,manage.py' manage.py test --noinput

after_script:
  - codecov
