# Generated by Django 2.2.4 on 2019-08-28 01:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('approval_type', models.CharField(choices=[('FIRST_BOOKED', 'First Booked'), ('DECLINE', 'Decline'), ('MANUAL', 'Manual')], default='FIRST_BOOKED', max_length=16)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invitee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='webhook_calendly.ApprovalGroup')),
            ],
            options={
                'ordering': ['email'],
            },
        ),
        migrations.CreateModel(
            name='BookingCalendlyData',
            fields=[
                ('payload', django.contrib.postgres.fields.jsonb.JSONField()),
                ('calendly_uuid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('approval_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='webhook_calendly.ApprovalGroup')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendly_data', to='bookings.Booking')),
            ],
        ),
    ]
