# Generated by Django 2.2.4 on 2019-08-29 04:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_calendly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingcalendlydata',
            name='payload',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
