# Generated by Django 2.2.4 on 2019-08-26 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_calendly', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitee',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
