# Generated by Django 2.2.4 on 2019-08-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_calendly', '0002_unique_email_invitee'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalgroup',
            name='approval_type',
            field=models.CharField(choices=[('FIRST_BOOKED', 'First Booked'), ('NO_APPROVAL', 'No Approval')], default='FIRST_BOOKED', max_length=16),
        ),
    ]
