# Generated by Django 2.2.4 on 2019-08-27 02:13

from django.db import migrations, models


def update_no_approval(apps, schema_editor):
    Client = apps.get_model('webhook_calendly', 'approvalgroup')
    Client.objects.filter(approval_type='NO_APPROVAL').update(approval_type='DECLINED')


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_calendly', '0003_approvalgroup_approval_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalgroup',
            name='approval_type',
            field=models.CharField(choices=[('FIRST_BOOKED', 'First Booked'), ('DECLINED', 'Declined'), ('MANUAL', 'Manual')], default='FIRST_BOOKED', max_length=16),
        ),
        migrations.RunPython(update_no_approval),
    ]
