# Generated by Django 2.2.4 on 2019-08-27 02:48

from django.db import migrations, models


def update_declined(apps, schema_editor):
    Client = apps.get_model('webhook_calendly', 'approvalgroup')
    Client.objects.filter(approval_type='DECLINED').update(approval_type='DECLINE')


class Migration(migrations.Migration):

    dependencies = [
        ('webhook_calendly', '0004_approval_type_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalgroup',
            name='approval_type',
            field=models.CharField(choices=[('FIRST_BOOKED', 'First Booked'), ('DECLINE', 'Decline'), ('MANUAL', 'Manual')], default='FIRST_BOOKED', max_length=16),
        ),
        migrations.RunPython(update_declined),
    ]
