# Generated by Django 2.2.4 on 2019-08-23 21:33

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('emails', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('spot_start', models.DateTimeField()),
                ('spot_end', models.DateTimeField()),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('calendly_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Updated at')),
                ('approved_for_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bookings.Group')),
            ],
        ),
    ]
