# Generated by Django 2.2.4 on 2019-08-28 01:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type_id', models.CharField(db_index=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('spot_start', models.DateTimeField()),
                ('spot_end', models.DateTimeField()),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('approval_status', models.CharField(choices=[('NEW', 'New'), ('APPROVED', 'Approved'), ('DECLINED', 'Declined')], default='NEW', max_length=16)),
                ('approval_protected', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
            ],
            options={
                'proxy': True,
                'constraints': [],
                'verbose_name': 'Cancelled Booking',
                'indexes': [],
                'verbose_name_plural': 'Cancelled Bookings',
            },
            bases=('bookings.booking',),
        ),
    ]
