# Generated by Django 2.2.4 on 2019-08-23 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_invitee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='invitee',
            options={'ordering': ['email']},
        ),
    ]
