# Generated by Django 2.2.4 on 2019-08-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_change_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendly_uuid',
            field=models.CharField(default='', max_length=32, unique=True),
        ),
    ]
