# Generated by Django 2.2.4 on 2019-08-25 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_auto_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='calendly_event_type_id',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
    ]
