# Generated by Django 2.2.4 on 2019-08-26 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_split_calendly'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledBooking',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
                'constraints': [],
                'verbose_name': 'Cancelled Booking',
                'verbose_name_plural': 'Cancelled Bookings',
            },
            bases=('bookings.booking',),
        ),
    ]
